version: "3.8"

services:
  strapi:
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: swgokoggckkc44cs8s8wc4so  # Must match actual Postgres container name in Coolify
      DATABASE_PORT: 5432
      DATABASE_NAME: postgresql
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: fU53YmzYXQnf5lmxIrO6rbeqSskiJqcvEL67APxBlpNXGcN1zAKYt7Kv24OlDmJL
      NODE_ENV: production
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./public/uploads:/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - coolify

networks:
  coolify:
    external: true
