version: '3.8'

services:

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: L39KNym5x4wmrwwqIadzI2DN7gFL0W6uq5F5T8iNNxwZGiloyffx58muv4vSekf2
      POSTGRES_DB:       strapi            # ← match this to DATABASE_NAME below
    volumes:
      - db_data:/var/lib/postgresql/data

  strapi:
    build: .
    depends_on:
      - db
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT:   postgres
      DATABASE_HOST:     coolify-db               # ← use the service name
      DATABASE_PORT:     5432
      DATABASE_NAME:     postgresql-database            # ← match POSTGRES_DB above
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD:  L39KNym5x4wmrwwqIadzI2DN7gFL0W6uq5F5T8iNNxwZGiloyffx58muv4vSekf2
      NODE_ENV:          production
    volumes:
      - ./public:/app/public

volumes:
  db_data:
